### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tomalec**
- Bump Node on Travis to latest (12.9.0)
- Update all devDependencies
- Update all dependencies ~~except jsonpatcherproxy~~
- Add source map, do not minimize test bundle
- DRY, re-use existing tasks for `npm test`

This is a set of maintenance changes before migrating to ES Modules, dependencies ~~(except `JSONPatcherProxy`)~~ are updated to ES modules versions.

### CODE REVIEW

**Comment by tomalec** [comment]
Edge to pass requires https://github.com/Starcounter-Jack/JSON-Patch/pull/238

**Comment by tomalec** [comment]
> Clean npm install shows errors in websocket package on Windows

Do you mean this one?

```bash
$ npm install

> websocket@1.0.29 install D:\repos\web\tmp\Palindrom\node_modules\websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)


D:\repos\web\tmp\Palindrom\node_modules\websocket>if not defined npm_config_node_gyp (node "C:\Users\tomalec\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\tomalec\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

...

```


-----

> however the file `docs/01-_Installation.md` definitely needs updating

Really, what exactly? I thought it's a non breaking change

**Comment by warpech** [comment]
> Really, what exactly? I thought it's a non breaking change

Sorry, my bad, I thought ES Modules are in this PR. My comment about docs was incorrect.

> Do you mean this one?

Yes:

image

**Comment by tomalec** [comment]
> > Do you mean this one?
>
> Yes:

Hm.. your log seem more elaborate than mine, but I think it's a `websocket` issue, that luckily does not affect us, hopefully will be fixed with their update.

**Pull request merged**
