### PR TITLE
Truncate readme, link to website, and docs folder

### PR DESCRIPTION
**Pull request by alshakero**
Now Palindrom website automatically scans `docs` folder and adds each MD file as a docs section. If there wasn't a `docs` folder in the repo (old releases) it will fail-over to README.md as the only section.

This way we can have multiple MD files in `docs` folder and edit them along the development in the same repo with zero effort on the website. 

This is documented in the development section in `docs/01-main.md`.

I intend to use the same mechanism for JSONPatch upcoming website.

### CODE REVIEW

**Comment by warpech** [comment]
Looking nice, but can you say what's the purpose, since you are concatenating the pages for presentation anyway?

Btw. any plans to merge `palindrom-website` to the Palindrom repo, presumably as `gh-pages` branch?

**Comment by alshakero** [comment]
> Looking nice, but can you say what's the purpose, since you are concatenating the pages for presentation anyway?

I'm not concatenating the pages 💃! I didn't release the new website version yet. There is now a drop-down menu that allows you to choose the section. Having one long piece doesn't look great. I'll release the website once the docs are up. I tested it, but would like to test it one more time with real-life data. That's why I am waiting for the merge.

> Btw. any plans to merge palindrom-website to the Palindrom repo, presumably as gh-pages branch?

I moved it yesterday 🎉 to https://github.com/Palindrom/palindrom.github.io. And that's the only way to have `https://palindrom.github.io` working without a pathname.

**Comment by warpech** [comment]
Now I get it, thanks. Looks fine for me. Maybe @tomalec has some comments?

**Comment by alshakero** [comment]
I'll merge this for now and would be more than happy to revert/change anything if requested.

**Comment by tomalec** [comment]
I'd leave the "Usage" and "Demos" section. I think it's good to advertise how  easy is the manipulation on shared object and to give a shortest possible path to see the demo.

**Comment by tomalec** [comment]
We could move that Usage to the top, and replace this snippet with `PalindormDOM` whi I really have no idea what is about to show.

**Comment by alshakero** [comment]
This is what I am talking about https://palindrom.github.io/#/docs/New-docs-hierarchy.

This url is temporarly valid for this branch. There will be each release's docs + master.

With Hash-router-aware section links 💃 => all links are permalinks and local storage cached for speeed ⚡️

**Comment by tomalec** [comment]
Cool, I'd just add small not to our tiny code sample, to make it clearer what's so awesome about Palindrom:
```js
/**
 * Defines a connection to a remote PATCH server, gives an object that is persistent between browser and server
 */
var palindrom = new Palindrom({remoteUrl: window.location.href});

// ...
// use palindrom.obj
palindrom.obj.someProperty = "new value";
// Your change gets propagated automatically to the remote, no glue code needed.
```

**Pull request merged**
