### PR TITLE
Call onPatchReceived before validation

### PR DESCRIPTION
**Pull request by alshakero**
I moved onPatchReceived higher in the code to call it before doing anything. And added tests.

Fixes: https://github.com/Palindrom/Palindrom/issues/193

### CODE REVIEW

**Comment by warpech** [comment]
Can you pls commit code reformatting on a separate commit? That makes the review much easier.

**Comment by alshakero** [comment]
> In future, can you pls commit code reformatting on a separate commit? That makes the review much easier.

I know your pain, but it's super annoying that I have to format the code manually while I'm actually fixing the issue in hand and never format. I can't "right click -> format", which I do like every 10 mins to check for syntax errors in 1 second.

**Comment by warpech** [comment]
> I know your pain, but it's super annoying that I have to format the code manually while I'm actually fixing the issue on hand. I can't "right click -> format", which I do like every 10 mins to check for syntax errors in 1 second.

What you can do, is reformat the file before making the changes and commit only that.

**Comment by alshakero** [comment]
Wow that's a great idea!

**Pull request merged**
