### PR TITLE
Expose version

### PR DESCRIPTION
**Pull request by alshakero**
Fixes: https://github.com/Palindrom/Palindrom/issues/177

### Interestring files to review:

https://github.com/Palindrom/Palindrom/compare/Expose-version?expand=1#diff-65cd67b3d902578b837a1beb95e5f596

https://github.com/Palindrom/Palindrom/compare/Expose-version?expand=1#diff-92b698a38d3db0381546f440a80e631b

### CODE REVIEW

**Comment by alshakero** [comment]
You can easily define a variable using `DefinePlugin` webpack. But I want Palindrom to work in Node too. That's why the `require` needs to be there. If we define a var using webpack, Node won't see it. 

Current method is the only method that is node + webpack friendly.

**Comment by tomalec** [comment]
Can't we then keep it static and bump it with version bump task?

**Comment by alshakero** [comment]
Does `Palindrom.version` have to be performant? It's a debugging variable that is ok to take 5 seconds to resolve, let alone 1µs.

**Comment by alshakero** [comment]
In fact, it takes 1.2551 **nano**second. 
image


Here: https://run.perf.zone/view/Palindromversion-1512132467434

**Comment by tomalec** [comment]
But you are paying the cost not when you access it(while debugging), but when you define the class(every time), so I'd rather compare parsing bundles. To me, it's more about a code maintenance.

Why do I have to bother about importing another package in runtime? Does it deliver any additional functionality? Why Do I need to read those 7 lines (ok comparing to thausands is't nothing. But to track the source on production (bumdeled), tracking where it came from is an action that could be avioded, plus it blurs the picture by attaching such dummy dependency to the list of meaningfull ones.

Also, as it is for debuging, I'd love to be able to find this value by just reading https://github.com/Palindrom/Palindrom/blob/f94ac32f4ab85034a59a98aea533faa12dd71eeb/src/palindrom.js and currently, I'm not able, as I either need to read https://github.com/Palindrom/Palindrom/blob/f94ac32f4ab85034a59a98aea533faa12dd71eeb/dist/palindrom-dom.js which is uglified as hell, and already have it in the comment, or read `package.json` which does not introduce any new value.

To me it's like using sledgehammer to crack a peanut, but other than that I had no other comments. So feel free to merge it, as having this in place is more important that juggling personal opinions ;)

**Comment by alshakero** [comment]
Version is hardcoded and bumped when you can `npm version` now. This should be better.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Palindrom/Palindrom/releases/tag/v3.1.0
- published on npm https://www.npmjs.com/package/palindrom
- included in a Finished release of SCF https://github.com/Starcounter/StarcounterClientFiles/releases/tag/2.1.1

**Pull request merged**
