### PR TITLE
Update test libraries (mocha & chai) for better security

### PR DESCRIPTION
**Pull request by alshakero**
Related https://github.com/Starcounter/StarcounterClientFiles/issues/76

### CODE REVIEW

**Comment by alshakero** [comment]
Tests are blocked by https://github.com/Starcounter/UniformDocs/issues/332

**Comment by warpech** [comment]
https://github.com/Starcounter/UniformDocs/issues/332 is probably closeable now

**Comment by alshakero** [comment]
Yes. They're blocked by https://github.com/Starcounter/Blending/issues/256 now.

**Comment by warpech** [comment]
Seems fixed now.

**Comment by alshakero** [comment]
Not really. But I don't understand what's going on. Tests on UniformDocs master [pass ](https://teamcity.starcounter.org/viewLog.html?buildId=61801&buildTypeId=Apps_UniformDocs_UniformDocsMaster24branchWithStarcounterDevelopNightly)(I run them now) and yet they fail [here](https://teamcity.starcounter.org/viewLog.html?buildId=61794&buildTypeId=Apps_WebPlatform_Palindrom_TestWithApps&tab=buildResultsDiv). And I verified that both actually use `Uniform#master` (not `master-2.4`).

**Comment by warpech** [comment]
>>> Yes. They're blocked by Starcounter/Blending#256 now.

>> Seems fixed now.

> Not really

https://github.com/Starcounter/Blending/issues/256 is closed and tests of Blending are passing, so I think you are talking about a new issue now.

**Comment by alshakero** [comment]
Waiting for https://github.com/Starcounter/UniformDocs/pull/345

**Comment by alshakero** [comment]
This is driving me crazy at this point. I fixed UniformDocs tests only for it and they're passing on master but failing here. 

Fixing UD tests here: https://github.com/Starcounter/UniformDocs/pull/345

@joozek78 could you help? Tests here run UniformDocs#master tests and they seem to be failing. And when I run UniformDocs#master independently they pass. See all green [here](https://github.com/Starcounter/UniformDocs/commits/master). Any idea what's going on?

**Comment by warpech** [comment]
If I am not wrong, you are getting crazy by the fact that the build [23](https://teamcity.starcounter.org/viewLog.html?buildId=61937&buildTypeId=Apps_WebPlatform_Palindrom_TestWithApps), which was started on 2018-07-30 16:03 does not include the fix `e060948` that you merged to UniformDocs `master` at 16:01. 

I can see in the "Depencencies" tab of that build, that the version `3c32f65` of UniformDocs dependency was used instead of the expected version `e060948`.

This is indeed strange. It seems like TeamCity had a bad day and did not refresh the dependencies, even though it was 2 minutes between merging in UniformDocs and running the build [23](https://teamcity.starcounter.org/viewLog.html?buildId=61937&buildTypeId=Apps_WebPlatform_Palindrom_TestWithApps). @joozek78, @ubbeK maybe you have some idea why is that?

Anyway, the "solution" is very simple. Just re-run the build manually. I just did that and the build [24](https://teamcity.starcounter.org/viewLog.html?buildId=62449&buildTypeId=Apps_WebPlatform_Palindrom_TestWithApps) passed the tests that previously failed... But two other tests fail now :/

I am starting build [25](https://teamcity.starcounter.org/viewLog.html?buildId=62450&buildTypeId=Apps_WebPlatform_Palindrom_TestWithApps) to check if that's repetitive.

**Comment by alshakero** [comment]
Great idea to actually compare hashes rather than whole branches. I was just checking if it's `master`. I had unhealthy trust in TeamCity 😄

**Comment by warpech** [comment]
I am surprised `Starcounter.Internal.CurrentVersion.Version` works at all in the test project, because the `UniformDocs.Tests` is not a Starcounter app. It is a NUnit test project.

I wonder where does the actual value come from in that case.

For the time being, I recommend to just check if *looks like* a Starcounter version number.

**Comment by alshakero** [comment]
PR for the comment above in https://github.com/Starcounter/UniformDocs/pull/352

**Pull request merged**
